### ISSUE TITLE
Blazor bundling and resources

### ISSUE THREAD

**Issue by HankiDesign** [telerik/blazor-docs#10]
The [Built-In Themes](https://docs.telerik.com/blazor-ui/themes) article mentions that the way Blazor handles bundling and resources is still unclear. However, it looks like Microsoft has now finalized the implementation and closed the [relevant issue](https://github.com/aspnet/AspNetCore/issues/6349).

As far as I understood, the documentation on their side is still not up to date so it might make sense to wait a bit instead of relying on all the scattered information in that message chain.

**Comment by marin-bratanov** [comment]
Thank you for reaching out.

Yes, there are indications on how this will work, and we will wait for them to release the code, so we can actually play with it, and perhaps for them to ship some docs. 

This is definitely on our radar, and we will document it as soon as it gets implemented in the actual codebase (after Preview 6).

**Comment by marin-bratanov** [comment]
The JS Interop file will be included as an asset from our package for the upcoming 1.2.0 release. The themes - not yet, as that requires much more work and consideration.

For the time being, the themes will keep being served through the CDN listed in the article, and when there is a change or a new way, I will update that article.

I will now close this issue through [https://github.com/telerik/blazor-docs/commit/58ed051eb73a6587c651fd4d87a88a5d3f77f96a](https://github.com/telerik/blazor-docs/commit/58ed051eb73a6587c651fd4d87a88a5d3f77f96a), [https://github.com/telerik/blazor-docs/commit/22430297c6672e3eded3bdf2ffaedd5d2ca34770](https://github.com/telerik/blazor-docs/commit/22430297c6672e3eded3bdf2ffaedd5d2ca34770) and [https://github.com/telerik/blazor-docs/commit/b749b2847ae35e8a82f56a58087a9cdd9b97756c](https://github.com/telerik/blazor-docs/commit/b749b2847ae35e8a82f56a58087a9cdd9b97756c), though.

**Comment by marin-bratanov** [comment]
A quick update - we just found some framework issues - purely client-side apps can't work with static assets and asp.net core hosted client apps need additional config [https://github.com/telerik/blazor-docs/commit/5597ce1b5526632c927f3b749babffd6403de970](https://github.com/telerik/blazor-docs/commit/5597ce1b5526632c927f3b749babffd6403de970).

**Comment by HankiDesign** [comment]
Thanks for the update Marin, interesting development.

**Comment by marin-bratanov** [comment]
Personally, I'm a little disappointed at how uncomfortable it is - enabling the static assets is an explicit step you must make, and it does not work at all for pure client Blazor apps. Let's hope it gets improved through [https://github.com/aspnet/AspNetCore/issues/10986](https://github.com/aspnet/AspNetCore/issues/10986)
