### ISSUE TITLE
Typo in textbox-add-icon article

### ISSUE THREAD

**Issue by jassent** [telerik/blazor-docs#1110]
I think this knowledge-base article has a typo:
[textbox-add-icon](https://github.com/telerik/blazor-docs/edit/master/knowledge-base/textbox-add-icon.md)

The class identifier is missing a space:
`/* icon with floating label */
    .tb-icon-container.with-label .k-icon {
        top: 0.7em;
    }`

Should be (space before .with-label):
`/* icon with floating label */
    .tb-icon-container .with-label .k-icon {
        top: 0.7em;
    }`

**Comment by dimodi** [comment]
I confirm the code is correct. The CSS rule targets elements that have both classes at the same time.
