### ISSUE TITLE
InCell Editing - Basics

### ISSUE THREAD

**Issue by CuriousDrive** [telerik/blazor-docs#118]
[Grid InCell Editing - Basics](https://docs.telerik.com/blazor-ui/components/grid/editing/incell#basics)

This part of the article says -  Cancellation of changes is not supported at the moment, you can prevent them by not calling the data access layer.

But when I click on the cancel button in InCell Editing mode then the action gets cancelled. Let me know if the line means something else.

**Comment by svdimitr** [comment]
Thank you, @CuriousDrive, for reporting that to us. I have updated the docs - https://github.com/telerik/blazor-docs/commit/f7b8cfcf77bdf37c9374091af42bb21e1f70bf1e
