### ISSUE TITLE
Typo in Grid - Display Format

### ISSUE THREAD

**Issue by JarRami** [telerik/blazor-docs#1845]
In the [Grid - Display Format](https://docs.telerik.com/blazor-ui/components/grid/columns/display-format) page it says in the Notes section "The CurrentInfo.CurrentCulture is used when rendering the formats, so if you need specific formats for specific users, you must set the culture of the app accordingly."

I think that needs to say CultureInfo.CurrentCulture?

**Comment by dimodi** [comment]
Thanks, @JarRami !
