### ISSUE TITLE
Blazor icon list is broken

### ISSUE THREAD

**Issue by jmaillet** [telerik/blazor-docs#224]
https://docs.telerik.com/blazor-ui/common-features/font-icons#icons-list

It shows a message saying to come here and open an issue

**Comment by marin-bratanov** [comment]
Oops, that wasn't meant to close automatically :)

I have just promoted a fix live, could you take a peek and see if it is OK now?

**Comment by jmaillet** [comment]
Looks good. Thanks!

**Comment by marin-bratanov** [comment]
Thank you for confirming and for pointing it out in the first place!
