### ISSUE TITLE
Copy paste(?) error in TreeList - Virtual scrolling

### ISSUE THREAD

**Issue by JarRami** [telerik/blazor-docs#2407]
On the page [TreeList - virtual scrolling](https://docs.telerik.com/blazor-ui/components/treelist/virtual-scrolling) above the code example it says "Enable Sorting in Telerik TreeList" but it might be better if it said something about virtual scrolling?

**Comment by dimodi** [comment]
Thanks, @JarRami !

https://github.com/telerik/blazor-docs/commit/5ac965e5c8833569b98ec2643b8df37615d634f3
