### ISSUE TITLE
TelerikTreeList example in Gantt Data Binding to Hierarchical Data

### ISSUE THREAD

**Issue by Dennis-Smurf** [telerik/blazor-docs#457]
**Is there wrong information? **
The example on https://docs.telerik.com/blazor-ui/components/gantt/gantt-tree/data-binding/hierarchical-data belongs to TelerikTreeList and is not TelerikGantt.

![image](https://user-images.githubusercontent.com/4238339/131795417-833f7a35-0842-4bef-a385-6116beb35863.png)

**Comment by svdimitr** [comment]
Hello Dennis, 

Thank you for reporting that to us, and excuse us for the late answer!

The code snippet was replaced with the suitable one in this commit: https://github.com/telerik/blazor-docs/commit/8ac1d9176bf1c15098717a962fb5026cd40c82e1
