### ISSUE TITLE
The TimeLine View page refers to Resource Grouping in the Day View rather than TimeLine view

### ISSUE THREAD

**Issue by lukasTheGrey** [telerik/blazor-docs#519]
https://docs.telerik.com/blazor-ui/components/scheduler/views/timeline

The timeline view page has a heading "Resource Grouping in the Day View" which should probably read "Resource Grouping in the TimeLine View".

The image above the heading is also from the day view. I guess someone just copy and pasted it?

**Comment by xristianstefanov** [comment]
Hi! Thank you for noticing and reporting. We've made changes with this PR: https://github.com/telerik/blazor-docs/pull/579
