### ISSUE TITLE
Missing DownColorField from Candlestick docs

### ISSUE THREAD

**Issue by marin-bratanov** [telerik/blazor-docs#525]
**Is there wrong information? **
Missing info

**Is there a code snippet that does not work or throws errors?**
No

**Something else**
The Candlestick article mentions the DownColor and ColorField, but does not mention the DownColorField and that ColorField values won't take priority over DownColor alone.  See my comments at https://www.telerik.com/forums/colorfield-on-candlestick

**Comment by svdimitr** [comment]
Done with https://github.com/telerik/blazor-docs/pull/699
