### ISSUE TITLE
Misspelled CRUD

### ISSUE THREAD

**Issue by nadcraker** [telerik/blazor-docs#53]
On page https://docs.telerik.com/blazor-ui/components/listview/templates it says "Declaring an edit template in the ListView. Note: The **CUD** operations are not implemented in this example."

It probably should say Declaring an edit template in the ListView. Note: The **CRUD** operations are not implemented in this example.

**Comment by marin-bratanov** [comment]
Thank you for reaching out!

There is a mimic for the **R**ead operation - data is provided to the component, so it's the **C**reate, **U**pdate and **D**elete operations that are not implemented.
