### ISSUE TITLE
Missing checkbox (bool) validation example

### ISSUE THREAD

**Issue by marin-bratanov** [telerik/blazor-docs#632]
You can find one in the demo https://demos.telerik.com/blazor-ui/checkbox/validation

but not in the docs https://docs.telerik.com/blazor-ui/common-features/input-validation

**Comment by ntacheva** [comment]
A CheckBox validation example is included in the Simple Inputs section of the Input Validation article - https://docs.telerik.com/blazor-ui/common-features/input-validation#simple-inputs.
