### ISSUE TITLE
AutoComplete Docs - Feature Section

### ISSUE THREAD

**Issue by CuriousDrive** [telerik/blazor-docs#92]
The "**Class**" feature section of the **AutoComplete** mentions combo box. This is what it says.

The **AutoComplete** provides the following features:
Class - the CSS class that will be rendered on the main wrapping element of the **combobox**.

I guess you will need to replace **combobox** with **autocomplete** ?

**Comment by svdimitr** [comment]
Hello, thank you @CuriousDrive for reporting that to us. The documentation is now live with the fix included: https://docs.telerik.com/blazor-ui/components/autocomplete/overview
